<a href="https://colab.research.google.com/github/sylle321/Hotel_booking/blob/main/BA305_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [162]:
import pandas as pd
path = "/hotels.csv"
df = pd.read_csv(path)
#Shows each columns data type and number of non-null values.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [163]:
#Counts distinct values in each column of the dataframe.
df.nunique()

hotel                                2
is_canceled                          2
lead_time                          479
arrival_date_year                    3
arrival_date_month                  12
arrival_date_week_number            53
arrival_date_day_of_month           31
stays_in_weekend_nights             17
stays_in_week_nights                35
adults                              14
children                             5
babies                               5
meal                                 5
country                            177
market_segment                       8
distribution_channel                 5
is_repeated_guest                    2
previous_cancellations              15
previous_bookings_not_canceled      73
reserved_room_type                  10
assigned_room_type                  12
booking_changes                     21
deposit_type                         3
agent                              333
company                            352
days_in_waiting_list               128
customer_type                        4
adr                               8879
required_car_parking_spaces          5
total_of_special_requests            6
reservation_status                   3
reservation_status_date            926
dtype: int64

In [172]:
# Convert hotel to a dummy variable:
# Resort Hotel = 0, City Hotel = 1
df['hotel'] = df['hotel'].map({
    'Resort Hotel': 0,
    'City Hotel': 1
})

df.head()

# Create dummy variables for the other categorical variables
categorical_cols = [
    'deposit_type',
    'market_segment',
    'customer_type',
    'reserved_room_type'
]

df_encoded = pd.get_dummies(
    df,
    columns=categorical_cols,
    drop_first=True,
    dtype=int
)

df_encoded.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type_Transient-Party,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,reserved_room_type_P
0,NaN,0,342,2015,July,27,1,0,0,2,...,0,0,1,0,0,0,0,0,0,0
1,NaN,0,737,2015,July,27,1,0,0,2,...,0,0,1,0,0,0,0,0,0,0
2,NaN,0,7,2015,July,27,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,NaN,0,13,2015,July,27,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,NaN,0,14,2015,July,27,1,0,2,2,...,0,0,0,0,0,0,0,0,0,0

In [165]:
# Selecting the columns of interest for analysis
# Making sure unrelated columns are not included in the analysis.
cols = [
    "hotel",
    "is_canceled",
    "lead_time",
    "deposit_type",
    "previous_cancellations",
    "previous_bookings_not_canceled",
    "customer_type",
    "booking_changes",
    "is_repeated_guest",
    "market_segment",
    "total_of_special_requests",
    "stays_in_weekend_nights",
    "stays_in_week_nights",
    "reserved_room_type",
    "adr",
    "distribution_channel",
    "arrival_date_month"
]

hotel_selected = df[cols]

hotel_selected.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 17 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           0 non-null       float64
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   deposit_type                    119390 non-null  object
 4   previous_cancellations          119390 non-null  int64
 5   previous_bookings_not_canceled  119390 non-null  int64
 6   customer_type                   119390 non-null  object
 7   booking_changes                 119390 non-null  int64
 8   is_repeated_guest               119390 non-null  int64
 9   market_segment                  119390 non-null  object
 10  total_of_special_requests       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  reserved_room_type              119390 non-null  object
 14  adr                             119390 non-null  float64
 15  distribution_channel            119390 non-null  object
 16  arrival_date_month              119390 non-null  object
dtypes: float64(2), int64(9), object(6)
memory usage: 15.5+ MB

In [166]:
#Cleaning the data by removing rows with any missing values and resetting the index.
hotel_clean = hotel_selected.dropna(how="any") #Removes rows with any missing values.
hotel_clean = hotel_clean.reset_index(drop=True) #resets the index

print(hotel_selected.shape)
print(hotel_clean.shape)

(119390, 17)
(0, 17)

In [167]:
#Checking cancelation counts and proportions in the cleaned dataset.
print(hotel_clean["is_canceled"].value_counts()) #Gives the count of each unique value in the "is_canceled" column.

print(
    hotel_clean["is_canceled"].value_counts(normalize=True) # Gives the proportion of each unique value in the "is_canceled" column.
)

Series([], Name: count, dtype: int64)
Series([], Name: proportion, dtype: float64)

In [168]:
# Calculate the correlation using PCA lab's code as reference.
# We exclude categorical string columns and only keep truly numeric columns
numeric_cols = [
    "is_canceled",
    "lead_time",
    "previous_cancellations",
    "previous_bookings_not_canceled",
    "booking_changes",
    "is_repeated_guest",
    "total_of_special_requests",
    "stays_in_weekend_nights",
    "stays_in_week_nights",
    "adr"
]

hotel_numeric = hotel_clean[numeric_cols]

corr_mat = hotel_numeric.corr()

corr_mat.round(4)

,is_canceled,lead_time,previous_cancellations,previous_bookings_not_canceled,booking_changes,is_repeated_guest,total_of_special_requests,stays_in_weekend_nights,stays_in_week_nights,adr
is_canceled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lead_time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
previous_cancellations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
previous_bookings_not_canceled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
booking_changes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_repeated_guest,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_of_special_requests,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
stays_in_weekend_nights,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
stays_in_week_nights,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [169]:
# Correlation with is_canceled only
corr_mat[["is_canceled"]].round(3)

                                is_canceled
is_canceled                             NaN
lead_time                               NaN
previous_cancellations                  NaN
previous_bookings_not_canceled          NaN
booking_changes                         NaN
is_repeated_guest                       NaN
total_of_special_requests               NaN
stays_in_weekend_nights                 NaN
stays_in_week_nights                    NaN
adr                                     NaN